language: c
sudo: false

env:
  global:
    - PATH=$HOME/.crenv/bin:$PATH
  matrix:
    - CRYSTAL_VERSION=0.9.1
    - CRYSTAL_VERSION=0.10.2

install:
  - curl -L https://raw.github.com/pine613/crenv/master/install.sh | bash
  - eval "$(crenv init -)"
  - crenv install $CRYSTAL_VERSION
  - crenv global $CRYSTAL_VERSION
  - crystal --version

before_script:
  - make install

script:
  - make test

notifications:
  slack:
    secure: "aHOTDq4uGQ4a3qvmuU3d4gqaTDgTEnD8xozHOOx1IuMHauqLk1B8KMVlelfURiiaPHHgRaidHYpFhVpn4ei4qGWPULfEhuiP4zAlvlQOjg5GzoZkz/E0TvFGRu7D/UltafFJFiFkDBkvSVnVUFnsLbSpF/SWJeSZ/ToEGnWiOTHkA5URpszCmLRt85DXykpnl+uvd9pSJ0maio8JmyuJ6YDuoUJ1tJVL64IGt+JAeE0GdVP9FA9t5YEngrKiE4DPkGJcK31E4lQIUIZkkkQYVKwHLWTutI/ofYz/qxkVZpV22K3XmYMIwJY0btdaMYEhD9pdVxF/R/ZA+DKvR/S8dBpu1H8kpfgHiq2/V0CzWV1ux2pYmEqZ1ihJ1i5JldB6RCLmVjspKqiURw4ehbJ1TYmv6JOIU94+L3+QzaQxNaZST1qExfCH0DgDIwTB/3Sf+qxmorLRzXjNcmPfURl3m1IjWkDWFJrmMlbcWgQ1rENHTNf5Qzz+uo+G9FhI1PfN0bj/GTR3vrNFU1kuqSvl1I/vhODL8/MYxDd7ZL6HAfitEb9G8cBfWeEvi/D+L9UPT3oofAhF7VGPvL4agQJ7sDikM2W2mF3wtvnDGdkspzDyz88jS3SLS5+inzXOEaCe3NBTmAeYmqDW6RLNNeBeHJfl94rwApR6BQpAuL5tqfM="
